-- STEP 4: 서버 검증 후 승인된 파일만 RAW에 적재하는 batch 기반 파이프라인.
-- RAW 대상은 migration 시점에 강제하지 않는다. 실제 적재 시점에만 안전하게 검증한다.

create schema if not exists core;

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null check (import_type in ('usage_history', 'inventory', 'item_master', 'supplier_master', 'purchase_order', 'goods_receipt', 'sales_order', 'business_event')),
  import_mode text not null check (import_mode in ('append', 'upsert', 'replace')),
  total_rows integer not null default 0 check (total_rows >= 0), success_rows integer not null default 0 check (success_rows >= 0),
  warning_rows integer not null default 0 check (warning_rows >= 0), error_rows integer not null default 0 check (error_rows >= 0),
  status text not null default 'PARSED' check (status in ('PARSED', 'VALIDATED', 'IMPORTED', 'ROLLED_BACK', 'FAILED')),
  rollback_supported boolean generated always as (import_mode <> 'replace') stored,
  uploaded_by uuid not null references auth.users(id), uploaded_at timestamptz not null default now(),
  imported_by uuid references auth.users(id), imported_at timestamptz, rolled_back_by uuid references auth.users(id), rolled_back_at timestamptz,
  failure_code text, failure_message text,
  check (success_rows + warning_rows + error_rows <= total_rows)
);

create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null check (row_number > 0), original_data jsonb not null, normalized_data jsonb,
  source_record_id text not null, mapping_confirmed boolean not null default false,
  validation_status text check (validation_status in ('SUCCESS', 'WARNING', 'ERROR')), validated_at timestamptz,
  created_at timestamptz not null default now(), unique (batch_id, row_number)
);

create table if not exists core.column_mapping (
  mapping_id uuid primary key default gen_random_uuid(),
  import_type text not null check (import_type in ('usage_history', 'inventory', 'item_master', 'supplier_master', 'purchase_order', 'goods_receipt', 'sales_order', 'business_event')),
  source_header text not null, standard_field text not null, raw_column text not null,
  created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (import_type, source_header)
);

create table if not exists core.validation_error (
  validation_error_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade, row_number integer not null check (row_number > 0),
  field_name text, error_code text not null, error_message text not null,
  severity text not null check (severity in ('WARNING', 'ERROR')), original_value text, created_at timestamptz not null default now()
);

create table if not exists core.import_rollback_snapshot (
  snapshot_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade, import_type text not null, raw_table text not null,
  source_record_id text not null, raw_record jsonb not null, captured_at timestamptz not null default now(), restored_at timestamptz,
  unique (batch_id, raw_table, source_record_id)
);

create table if not exists core.forecast_data_change (
  change_id bigint generated by default as identity primary key,
  batch_id uuid not null unique references core.upload_batch(batch_id) on delete cascade,
  import_type text not null check (import_type in ('usage_history', 'sales_order', 'business_event')),
  changed_at timestamptz not null default now(), rolled_back_at timestamptz
);

-- 부분 실행된 이전 migration을 안전하게 보완한다. 누락/중복 source ID는 추측하여 보정하지 않는다.
alter table core.upload_batch add column if not exists failure_code text;
alter table core.upload_batch add column if not exists failure_message text;
alter table core.import_staging add column if not exists source_record_id text;
alter table core.import_staging add column if not exists mapping_confirmed boolean not null default false;
alter table core.import_staging add column if not exists validation_status text;
alter table core.import_rollback_snapshot add column if not exists source_record_id text;

do $$
begin
  if exists (select 1 from core.import_staging where source_record_id is null or btrim(source_record_id) = '') then
    raise exception 'IMPORT_STAGING_SOURCE_RECORD_ID_REQUIRED' using errcode = '22023';
  end if;
  if exists (select 1 from core.import_staging group by batch_id, source_record_id having count(*) > 1) then
    raise exception 'IMPORT_STAGING_SOURCE_RECORD_ID_DUPLICATE' using errcode = '22023';
  end if;
  if exists (select 1 from core.import_rollback_snapshot where source_record_id is null or btrim(source_record_id) = '') then
    raise exception 'IMPORT_ROLLBACK_SNAPSHOT_SOURCE_RECORD_ID_REQUIRED' using errcode = '22023';
  end if;
end $$;

alter table core.import_staging alter column source_record_id set not null;
alter table core.import_rollback_snapshot alter column source_record_id set not null;
create unique index if not exists import_staging_batch_source_record_id_unique on core.import_staging(batch_id, source_record_id);
create unique index if not exists import_rollback_snapshot_batch_target_source_unique on core.import_rollback_snapshot(batch_id, raw_table, source_record_id);
create index if not exists import_staging_batch_status_idx on core.import_staging(batch_id, validation_status);
create index if not exists validation_error_batch_severity_idx on core.validation_error(batch_id, severity, row_number);
create index if not exists import_rollback_snapshot_batch_idx on core.import_rollback_snapshot(batch_id);
create index if not exists upload_batch_uploaded_at_idx on core.upload_batch(uploaded_at desc);

create or replace view core.import_batch_summary with (security_invoker = true) as
select batch.batch_id, batch.file_name, batch.import_type, batch.import_mode, batch.total_rows, batch.success_rows, batch.warning_rows, batch.error_rows,
  batch.status, batch.rollback_supported, batch.uploaded_by, app_user.email as uploaded_by_email, app_user.name as uploaded_by_name,
  batch.uploaded_at, batch.imported_at, batch.rolled_back_at, batch.failure_code, batch.failure_message
from core.upload_batch as batch left join core.app_user as app_user on app_user.user_id = batch.uploaded_by
where core.is_active_user() and (batch.uploaded_by = auth.uid() or core.is_admin());

-- payload의 실제 key만 명시적으로 INSERT한다. mapping에 없는 default/identity 컬럼은 생략된다.
create or replace function core.insert_import_raw_record(p_target_table text, p_payload jsonb)
returns void language plpgsql security definer set search_path = pg_catalog, core, raw as $$
declare column_list text; value_list text; invalid_column_count integer;
begin
  if p_target_table not in ('usage_history', 'inventory', 'item_master', 'supplier_master', 'purchase_order', 'goods_receipt', 'sales_order', 'business_event')
     or to_regclass(format('raw.%I', p_target_table)) is null then
    raise exception 'IMPORT_TARGET_UNAVAILABLE' using errcode = '42P01';
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'IMPORT_RAW_PAYLOAD_COLUMN_UNSUPPORTED' using errcode = '22023';
  end if;
  if (select count(*) from information_schema.columns where table_schema = 'raw' and table_name = p_target_table
        and column_name in ('batch_id', 'source_type', 'loaded_at', 'source_record_id')) <> 4 then
    raise exception 'IMPORT_TARGET_UNAVAILABLE' using errcode = '42703';
  end if;
  select count(*) into invalid_column_count
  from jsonb_object_keys(p_payload) as payload_key(column_name)
  left join information_schema.columns as column_info on column_info.table_schema = 'raw'
    and column_info.table_name = p_target_table and column_info.column_name = payload_key.column_name
  where column_info.column_name is null or column_info.is_generated = 'ALWAYS' or column_info.identity_generation = 'ALWAYS';
  if invalid_column_count <> 0 then raise exception 'IMPORT_RAW_PAYLOAD_COLUMN_UNSUPPORTED' using errcode = '22023'; end if;
  select string_agg(format('%I', attribute.attname), ', ' order by attribute.attnum),
    string_agg(format('case when $1 -> %1$L is null or $1 -> %1$L = ''null''::jsonb then null else ($1 ->> %1$L)::%2$s end',
      attribute.attname, format_type(attribute.atttypid, attribute.atttypmod)), ', ' order by attribute.attnum)
  into column_list, value_list
  from pg_attribute as attribute
  where attribute.attrelid = to_regclass(format('raw.%I', p_target_table)) and attribute.attnum > 0 and not attribute.attisdropped
    and attribute.attname in (select jsonb_object_keys(p_payload));
  if column_list is null or value_list is null then raise exception 'IMPORT_RAW_PAYLOAD_COLUMN_UNSUPPORTED' using errcode = '22023'; end if;
  execute format('insert into raw.%I (%s) select %s', p_target_table, column_list, value_list) using p_payload;
end;
$$;

create or replace function core.import_approved_batch(uuid, text default null)
returns core.upload_batch language plpgsql security definer set search_path = pg_catalog, core, raw as $$
declare p_batch_id alias for $1; replace_confirmation alias for $2; batch_row core.upload_batch; staging_row core.import_staging;
  target_table text; imported_at_value timestamptz := now(); raw_payload jsonb; target_has_duplicates boolean;
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED' using errcode = '42501'; end if;
  select * into batch_row from core.upload_batch where upload_batch.batch_id = p_batch_id for update;
  if batch_row.batch_id is null then raise exception 'IMPORT_BATCH_NOT_FOUND' using errcode = 'P0002'; end if;
  if batch_row.status <> 'VALIDATED' then raise exception 'IMPORT_BATCH_NOT_VALIDATED' using errcode = '22023'; end if;
  if batch_row.error_rows <> 0 then raise exception 'IMPORT_BATCH_HAS_ERRORS' using errcode = '22023'; end if;
  if batch_row.import_mode = 'replace' and replace_confirmation is distinct from 'REPLACE' then raise exception 'REPLACE_CONFIRMATION_REQUIRED' using errcode = '22023'; end if;
  if not exists (select 1 from core.import_staging where batch_id = p_batch_id) then raise exception 'IMPORT_STAGING_EMPTY' using errcode = '22023'; end if;
  if exists (select 1 from core.import_staging where batch_id = p_batch_id and (mapping_confirmed = false or validation_status is null
      or validation_status = 'ERROR' or normalized_data is null or source_record_id is null or btrim(source_record_id) = '')) then
    raise exception 'IMPORT_STAGING_NOT_APPROVED' using errcode = '22023';
  end if;
  if exists (select 1 from core.validation_error where batch_id = p_batch_id and severity = 'ERROR') then raise exception 'IMPORT_BATCH_HAS_ERRORS' using errcode = '22023'; end if;
  target_table := case batch_row.import_type
    when 'usage_history' then 'usage_history' when 'inventory' then 'inventory' when 'item_master' then 'item_master' when 'supplier_master' then 'supplier_master'
    when 'purchase_order' then 'purchase_order' when 'goods_receipt' then 'goods_receipt' when 'sales_order' then 'sales_order' when 'business_event' then 'business_event' else null end;
  if target_table is null or to_regclass(format('raw.%I', target_table)) is null then raise exception 'IMPORT_TARGET_UNAVAILABLE' using errcode = '42P01'; end if;
  if (select count(*) from information_schema.columns where table_schema = 'raw' and table_name = target_table
      and column_name in ('batch_id', 'source_type', 'loaded_at', 'source_record_id')) <> 4 then raise exception 'IMPORT_TARGET_UNAVAILABLE' using errcode = '42703'; end if;
  if batch_row.import_mode = 'upsert' then
    execute format('select exists (select 1 from raw.%I as target join core.import_staging as staging on staging.batch_id = $1 and target.source_record_id = staging.source_record_id where target.source_type = ''FILE_UPLOAD'' group by target.source_record_id having count(*) > 1)', target_table)
      into target_has_duplicates using p_batch_id;
    if target_has_duplicates then raise exception 'IMPORT_UPSERT_TARGET_DUPLICATE' using errcode = '22023'; end if;
    execute format('insert into core.import_rollback_snapshot (batch_id, import_type, raw_table, source_record_id, raw_record) select distinct on (target.source_record_id) $1, $2, $3, target.source_record_id, to_jsonb(target) from raw.%I as target join core.import_staging as staging on staging.batch_id = $1 and target.source_record_id = staging.source_record_id where target.source_type = ''FILE_UPLOAD'' order by target.source_record_id', target_table)
      using p_batch_id, batch_row.import_type, target_table;
    execute format('delete from raw.%I as target using core.import_staging as staging where staging.batch_id = $1 and target.source_type = ''FILE_UPLOAD'' and target.source_record_id = staging.source_record_id', target_table) using p_batch_id;
  elsif batch_row.import_mode = 'replace' then
    execute format('delete from raw.%I where source_type = ''FILE_UPLOAD''', target_table);
  end if;
  for staging_row in select * from core.import_staging where batch_id = p_batch_id and validation_status in ('SUCCESS', 'WARNING') order by row_number loop
    if staging_row.source_record_id is null or btrim(staging_row.source_record_id) = '' then raise exception 'SOURCE_RECORD_ID_REQUIRED' using errcode = '22023'; end if;
    raw_payload := staging_row.normalized_data || jsonb_build_object('batch_id', p_batch_id, 'source_type', 'FILE_UPLOAD', 'loaded_at', imported_at_value, 'source_record_id', staging_row.source_record_id);
    perform core.insert_import_raw_record(target_table, raw_payload);
  end loop;
  update core.upload_batch set status = 'IMPORTED', imported_by = auth.uid(), imported_at = imported_at_value, failure_code = null, failure_message = null
    where batch_id = p_batch_id returning * into batch_row;
  if batch_row.import_type in ('usage_history', 'sales_order', 'business_event') then
    insert into core.forecast_data_change(batch_id, import_type, changed_at) values (p_batch_id, batch_row.import_type, imported_at_value)
    on conflict (batch_id) do update set import_type = excluded.import_type, changed_at = excluded.changed_at, rolled_back_at = null;
  end if;
  insert into core.audit_log(actor, action, target_type, target_id, after) values (auth.uid(), 'IMPORT_BATCH_IMPORTED', 'upload_batch', p_batch_id::text, to_jsonb(batch_row));
  return batch_row;
end;
$$;

create or replace function core.rollback_import_batch(uuid)
returns core.upload_batch language plpgsql security definer set search_path = pg_catalog, core, raw as $$
declare batch_row core.upload_batch; snapshot_row core.import_rollback_snapshot; target_table text; rollback_at_value timestamptz := now();
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED' using errcode = '42501'; end if;
  select * into batch_row from core.upload_batch where batch_id = $1 for update;
  if batch_row.batch_id is null then raise exception 'IMPORT_BATCH_NOT_FOUND' using errcode = 'P0002'; end if;
  if batch_row.status <> 'IMPORTED' then raise exception 'IMPORT_BATCH_NOT_ROLLBACK_READY' using errcode = '22023'; end if;
  if batch_row.import_mode = 'replace' then raise exception 'REPLACE_ROLLBACK_NOT_SUPPORTED' using errcode = '0A000'; end if;
  if exists (select 1 from core.upload_batch as later_batch where later_batch.import_type = batch_row.import_type and later_batch.status = 'IMPORTED' and later_batch.imported_at > batch_row.imported_at) then raise exception 'ROLLBACK_DEPENDENCY_EXISTS' using errcode = '55000'; end if;
  target_table := case batch_row.import_type
    when 'usage_history' then 'usage_history' when 'inventory' then 'inventory' when 'item_master' then 'item_master' when 'supplier_master' then 'supplier_master'
    when 'purchase_order' then 'purchase_order' when 'goods_receipt' then 'goods_receipt' when 'sales_order' then 'sales_order' when 'business_event' then 'business_event' else null end;
  if target_table is null or to_regclass(format('raw.%I', target_table)) is null then raise exception 'IMPORT_TARGET_UNAVAILABLE' using errcode = '42P01'; end if;
  if (select count(*) from information_schema.columns where table_schema = 'raw' and table_name = target_table and column_name in ('batch_id', 'source_type', 'loaded_at', 'source_record_id')) <> 4 then raise exception 'IMPORT_TARGET_UNAVAILABLE' using errcode = '42703'; end if;
  execute format('delete from raw.%I where batch_id = $1', target_table) using $1;
  if batch_row.import_mode = 'upsert' then
    for snapshot_row in select * from core.import_rollback_snapshot where batch_id = $1 order by snapshot_id loop
      perform core.insert_import_raw_record(target_table, snapshot_row.raw_record);
    end loop;
    update core.import_rollback_snapshot set restored_at = rollback_at_value where batch_id = $1;
  end if;
  update core.upload_batch set status = 'ROLLED_BACK', rolled_back_by = auth.uid(), rolled_back_at = rollback_at_value where batch_id = $1 returning * into batch_row;
  update core.forecast_data_change set rolled_back_at = rollback_at_value where batch_id = $1;
  insert into core.audit_log(actor, action, target_type, target_id, after) values (auth.uid(), 'IMPORT_BATCH_ROLLED_BACK', 'upload_batch', $1::text, to_jsonb(batch_row));
  return batch_row;
end;
$$;

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.column_mapping enable row level security;
alter table core.validation_error enable row level security;
alter table core.import_rollback_snapshot enable row level security;
alter table core.forecast_data_change enable row level security;
revoke all on core.upload_batch, core.import_staging, core.column_mapping, core.validation_error, core.import_rollback_snapshot, core.forecast_data_change, core.import_batch_summary from anon;
grant select, insert, update, delete on core.upload_batch, core.import_staging, core.column_mapping, core.validation_error to authenticated;
grant select on core.import_rollback_snapshot, core.forecast_data_change, core.import_batch_summary to authenticated;
grant usage, select on all sequences in schema core to authenticated;

drop policy if exists upload_batch_owner_select on core.upload_batch;
create policy upload_batch_owner_select on core.upload_batch for select to authenticated using (core.is_active_user() and (uploaded_by = auth.uid() or core.is_admin()));
drop policy if exists upload_batch_admin_mutation on core.upload_batch;
create policy upload_batch_admin_mutation on core.upload_batch for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists import_staging_owner_select on core.import_staging;
create policy import_staging_owner_select on core.import_staging for select to authenticated using (exists (select 1 from core.upload_batch as batch where batch.batch_id = import_staging.batch_id and core.is_active_user() and (batch.uploaded_by = auth.uid() or core.is_admin())));
drop policy if exists import_staging_admin_mutation on core.import_staging;
create policy import_staging_admin_mutation on core.import_staging for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists column_mapping_active_select on core.column_mapping;
create policy column_mapping_active_select on core.column_mapping for select to authenticated using (core.is_active_user());
drop policy if exists column_mapping_admin_mutation on core.column_mapping;
create policy column_mapping_admin_mutation on core.column_mapping for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists validation_error_owner_select on core.validation_error;
create policy validation_error_owner_select on core.validation_error for select to authenticated using (exists (select 1 from core.upload_batch as batch where batch.batch_id = validation_error.batch_id and core.is_active_user() and (batch.uploaded_by = auth.uid() or core.is_admin())));
drop policy if exists validation_error_admin_mutation on core.validation_error;
create policy validation_error_admin_mutation on core.validation_error for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists rollback_snapshot_admin_select on core.import_rollback_snapshot;
create policy rollback_snapshot_admin_select on core.import_rollback_snapshot for select to authenticated using (core.is_admin());
drop policy if exists rollback_snapshot_admin_mutation on core.import_rollback_snapshot;
create policy rollback_snapshot_admin_mutation on core.import_rollback_snapshot for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists forecast_data_change_active_select on core.forecast_data_change;
create policy forecast_data_change_active_select on core.forecast_data_change for select to authenticated using (core.is_active_user());
drop policy if exists forecast_data_change_admin_mutation on core.forecast_data_change;
create policy forecast_data_change_admin_mutation on core.forecast_data_change for all to authenticated using (core.is_admin()) with check (core.is_admin());

revoke all on function core.insert_import_raw_record(text, jsonb) from public, anon, authenticated;
revoke all on function core.import_approved_batch(uuid, text) from public, anon;
revoke all on function core.rollback_import_batch(uuid) from public, anon;
grant execute on function core.import_approved_batch(uuid, text) to authenticated;
grant execute on function core.rollback_import_batch(uuid) to authenticated;
