-- STEP 4: 서버 검증 후 승인된 파일만 RAW에 적재하는 batch 기반 파이프라인.
-- 이 migration은 기존 RAW 구조를 변경하지 않고 STEP 3 provenance 계약을 선행 검증한다.

create schema if not exists core;

do $$
declare
  target_table text;
  required_column text;
begin
  foreach target_table in array array[
    'usage_history',
    'inventory',
    'item_master',
    'supplier_master',
    'purchase_order',
    'goods_receipt',
    'sales_order',
    'business_event'
  ]
  loop
    if to_regclass(format('raw.%I', target_table)) is null then
      raise exception 'IMPORT_RAW_TABLE_REQUIRED: raw.%', target_table using errcode = '42P01';
    end if;

    foreach required_column in array array[
      'batch_id',
      'source_type',
      'loaded_at',
      'source_record_id'
    ]
    loop
      if not exists (
        select 1
        from information_schema.columns
        where table_schema = 'raw'
          and table_name = target_table
          and column_name = required_column
      ) then
        raise exception 'IMPORT_PROVENANCE_COLUMN_REQUIRED: raw.%.%', target_table, required_column
          using errcode = '42703';
      end if;
    end loop;
  end loop;
end $$;

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null check (import_type in (
    'usage_history', 'inventory', 'item_master', 'supplier_master',
    'purchase_order', 'goods_receipt', 'sales_order', 'business_event'
  )),
  import_mode text not null check (import_mode in ('append', 'upsert', 'replace')),
  total_rows integer not null default 0 check (total_rows >= 0),
  success_rows integer not null default 0 check (success_rows >= 0),
  warning_rows integer not null default 0 check (warning_rows >= 0),
  error_rows integer not null default 0 check (error_rows >= 0),
  status text not null default 'PARSED' check (status in (
    'PARSED', 'VALIDATED', 'IMPORTED', 'ROLLED_BACK', 'FAILED'
  )),
  rollback_supported boolean generated always as (import_mode <> 'replace') stored,
  uploaded_by uuid not null references auth.users(id),
  uploaded_at timestamptz not null default now(),
  imported_by uuid references auth.users(id),
  imported_at timestamptz,
  rolled_back_by uuid references auth.users(id),
  rolled_back_at timestamptz,
  failure_code text,
  failure_message text,
  check (success_rows + warning_rows + error_rows <= total_rows)
);

create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null check (row_number > 0),
  original_data jsonb not null,
  normalized_data jsonb,
  source_record_id text,
  mapping_confirmed boolean not null default false,
  validation_status text check (validation_status in ('SUCCESS', 'WARNING', 'ERROR')),
  validated_at timestamptz,
  created_at timestamptz not null default now(),
  unique (batch_id, row_number)
);

create table if not exists core.column_mapping (
  mapping_id uuid primary key default gen_random_uuid(),
  import_type text not null check (import_type in (
    'usage_history', 'inventory', 'item_master', 'supplier_master',
    'purchase_order', 'goods_receipt', 'sales_order', 'business_event'
  )),
  source_header text not null,
  standard_field text not null,
  raw_column text not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (import_type, source_header)
);

create table if not exists core.validation_error (
  validation_error_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null check (row_number > 0),
  field_name text,
  error_code text not null,
  error_message text not null,
  severity text not null check (severity in ('WARNING', 'ERROR')),
  original_value text,
  created_at timestamptz not null default now()
);

create table if not exists core.import_rollback_snapshot (
  snapshot_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  import_type text not null,
  raw_table text not null,
  source_record_id text,
  raw_record jsonb not null,
  captured_at timestamptz not null default now(),
  restored_at timestamptz
);

create table if not exists core.forecast_data_change (
  change_id bigint generated by default as identity primary key,
  batch_id uuid not null unique references core.upload_batch(batch_id) on delete cascade,
  import_type text not null check (import_type in ('usage_history', 'sales_order', 'business_event')),
  changed_at timestamptz not null default now(),
  rolled_back_at timestamptz
);

create index if not exists import_staging_batch_status_idx
  on core.import_staging(batch_id, validation_status);
create index if not exists validation_error_batch_severity_idx
  on core.validation_error(batch_id, severity, row_number);
create index if not exists import_rollback_snapshot_batch_idx
  on core.import_rollback_snapshot(batch_id);
create index if not exists upload_batch_uploaded_at_idx
  on core.upload_batch(uploaded_at desc);

create or replace view core.import_batch_summary
with (security_invoker = true) as
select
  batch.batch_id,
  batch.file_name,
  batch.import_type,
  batch.import_mode,
  batch.total_rows,
  batch.success_rows,
  batch.warning_rows,
  batch.error_rows,
  batch.status,
  batch.rollback_supported,
  batch.uploaded_by,
  app_user.email as uploaded_by_email,
  app_user.name as uploaded_by_name,
  batch.uploaded_at,
  batch.imported_at,
  batch.rolled_back_at,
  batch.failure_code,
  batch.failure_message
from core.upload_batch as batch
left join core.app_user as app_user on app_user.user_id = batch.uploaded_by
where core.is_active_user()
  and (batch.uploaded_by = auth.uid() or core.is_admin());

-- 승인 RPC는 고정 allowlist로만 RAW 대상 식별자를 선택한다. normalized_data는
-- repository 단계에서 실제 RAW 컬럼명을 key로 가진 JSON으로 저장되어야 한다.
create or replace function core.import_approved_batch(uuid, text default null)
returns core.upload_batch
language plpgsql
security definer
set search_path = core, raw, public
as $$
declare
  p_batch_id alias for $1;
  replace_confirmation alias for $2;
  batch_row core.upload_batch;
  staging_row core.import_staging;
  target_table text;
  imported_at_value timestamptz := now();
  source_type text = 'FILE_UPLOAD';
  record_source_id text;
  raw_payload jsonb;
begin
  if not core.is_admin() then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  select * into batch_row
  from core.upload_batch
  where upload_batch.batch_id = p_batch_id
  for update;

  if batch_row.batch_id is null then
    raise exception 'IMPORT_BATCH_NOT_FOUND' using errcode = 'P0002';
  end if;
  if batch_row.status <> 'VALIDATED' then
    raise exception 'IMPORT_BATCH_NOT_VALIDATED' using errcode = '22023';
  end if;
  if batch_row.error_rows <> 0 then
    raise exception 'IMPORT_BATCH_HAS_ERRORS' using errcode = '22023';
  end if;
  if batch_row.import_mode = 'replace'
     and replace_confirmation is distinct from 'REPLACE' then
    raise exception 'REPLACE_CONFIRMATION_REQUIRED' using errcode = '22023';
  end if;
  if not exists (
    select 1
    from core.import_staging
    where import_staging.batch_id = p_batch_id
  ) then
    raise exception 'IMPORT_STAGING_EMPTY' using errcode = '22023';
  end if;
  if exists (
    select 1
    from core.import_staging
    where import_staging.batch_id = p_batch_id
      and (
        mapping_confirmed = false
        or validation_status is null
        or validation_status = 'ERROR'
        or normalized_data is null
      )
  ) then
    raise exception 'IMPORT_STAGING_NOT_APPROVED' using errcode = '22023';
  end if;
  if exists (
    select 1
    from core.validation_error
    where validation_error.batch_id = p_batch_id
      and severity = 'ERROR'
  ) then
    raise exception 'IMPORT_BATCH_HAS_ERRORS' using errcode = '22023';
  end if;

  target_table := case batch_row.import_type
    when 'usage_history' then 'usage_history'
    when 'inventory' then 'inventory'
    when 'item_master' then 'item_master'
    when 'supplier_master' then 'supplier_master'
    when 'purchase_order' then 'purchase_order'
    when 'goods_receipt' then 'goods_receipt'
    when 'sales_order' then 'sales_order'
    when 'business_event' then 'business_event'
    else null
  end;
  if target_table is null then
    raise exception 'IMPORT_TYPE_NOT_SUPPORTED' using errcode = '22023';
  end if;

  if batch_row.import_mode = 'upsert' then
    execute format(
      'insert into core.import_rollback_snapshot '
      || '(batch_id, import_type, raw_table, source_record_id, raw_record) '
      || 'select $1, $2, $3, target.source_record_id, to_jsonb(target) '
      || 'from raw.%I as target '
      || 'join core.import_staging as staging '
      || 'on staging.batch_id = $1 '
      || 'and target.source_record_id = coalesce(staging.source_record_id, staging.row_number::text) '
      || 'where target.source_type = ''FILE_UPLOAD''',
      target_table
    ) using p_batch_id, batch_row.import_type, target_table;

    execute format(
      'delete from raw.%I as target using core.import_staging as staging '
      || 'where staging.batch_id = $1 '
      || 'and target.source_type = ''FILE_UPLOAD'' '
      || 'and target.source_record_id = coalesce(staging.source_record_id, staging.row_number::text)',
      target_table
    ) using p_batch_id;
  elsif batch_row.import_mode = 'replace' then
    execute format(
      'delete from raw.%I where source_type = ''FILE_UPLOAD''',
      target_table
    );
  end if;

  for staging_row in
    select *
    from core.import_staging
    where import_staging.batch_id = p_batch_id
      and validation_status in ('SUCCESS', 'WARNING')
    order by row_number
  loop
    record_source_id := coalesce(
      staging_row.source_record_id,
      p_batch_id::text || ':' || staging_row.row_number::text
    );
    raw_payload := staging_row.normalized_data || jsonb_build_object(
      'batch_id', p_batch_id,
      'source_type', source_type,
      'loaded_at', imported_at_value,
      'source_record_id', record_source_id
    );
    if source_type = 'FILE_UPLOAD'
       and raw_payload ->> 'source_type' = source_type then
      null;
    else
      raise exception 'IMPORT_PROVENANCE_INVALID' using errcode = '22023';
    end if;

    if batch_row.import_type = 'usage_history' and not (raw_payload ? 'usage_id') then
      raw_payload := raw_payload || jsonb_build_object('usage_id', record_source_id);
    elsif batch_row.import_type = 'sales_order' and not (raw_payload ? 'sales_order_id') then
      raw_payload := raw_payload || jsonb_build_object('sales_order_id', gen_random_uuid());
    elsif batch_row.import_type = 'business_event' and not (raw_payload ? 'business_event_id') then
      raw_payload := raw_payload || jsonb_build_object('business_event_id', gen_random_uuid());
    end if;

    execute format(
      'insert into raw.%1$I select (jsonb_populate_record(null::raw.%1$I, $1)).*',
      target_table
    ) using raw_payload;
  end loop;

  update core.upload_batch
  set status = 'IMPORTED',
      imported_by = auth.uid(),
      imported_at = imported_at_value,
      failure_code = null,
      failure_message = null
  where upload_batch.batch_id = p_batch_id
  returning * into batch_row;

  if batch_row.import_type in ('usage_history', 'sales_order', 'business_event') then
    insert into core.forecast_data_change(batch_id, import_type, changed_at)
    values (p_batch_id, batch_row.import_type, imported_at_value)
    on conflict (batch_id) do update
      set import_type = excluded.import_type,
          changed_at = excluded.changed_at,
          rolled_back_at = null;
  end if;

  insert into core.audit_log(actor, action, target_type, target_id, after)
  values (auth.uid(), 'IMPORT_BATCH_IMPORTED', 'upload_batch', p_batch_id::text, to_jsonb(batch_row));

  return batch_row;
end;
$$;

create or replace function core.rollback_import_batch(uuid)
returns core.upload_batch
language plpgsql
security definer
set search_path = core, raw, public
as $$
declare
  batch_row core.upload_batch;
  snapshot_row core.import_rollback_snapshot;
  target_table text;
  rollback_at_value timestamptz := now();
begin
  if not core.is_admin() then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  select * into batch_row
  from core.upload_batch
  where batch_id = $1
  for update;

  if batch_row.batch_id is null then
    raise exception 'IMPORT_BATCH_NOT_FOUND' using errcode = 'P0002';
  end if;
  if batch_row.status <> 'IMPORTED' then
    raise exception 'IMPORT_BATCH_NOT_ROLLBACK_READY' using errcode = '22023';
  end if;
  if batch_row.import_mode = 'replace' then
    raise exception 'REPLACE_ROLLBACK_NOT_SUPPORTED' using errcode = '0A000';
  end if;
  if exists (
    select 1
    from core.upload_batch as later_batch
    where later_batch.import_type = batch_row.import_type
      and later_batch.status = 'IMPORTED'
      and later_batch.imported_at > batch_row.imported_at
  ) then
    raise exception 'ROLLBACK_DEPENDENCY_EXISTS' using errcode = '55000';
  end if;

  target_table := case batch_row.import_type
    when 'usage_history' then 'usage_history'
    when 'inventory' then 'inventory'
    when 'item_master' then 'item_master'
    when 'supplier_master' then 'supplier_master'
    when 'purchase_order' then 'purchase_order'
    when 'goods_receipt' then 'goods_receipt'
    when 'sales_order' then 'sales_order'
    when 'business_event' then 'business_event'
    else null
  end;
  if target_table is null then
    raise exception 'IMPORT_TYPE_NOT_SUPPORTED' using errcode = '22023';
  end if;

  execute format('delete from raw.%I where batch_id = $1', target_table) using $1;

  if batch_row.import_mode = 'upsert' then
    for snapshot_row in
      select *
      from core.import_rollback_snapshot
      where batch_id = $1
      order by snapshot_id
    loop
      execute format(
        'insert into raw.%1$I select (jsonb_populate_record(null::raw.%1$I, $1)).*',
        target_table
      ) using snapshot_row.raw_record;
    end loop;

    update core.import_rollback_snapshot
    set restored_at = rollback_at_value
    where batch_id = $1;
  end if;

  update core.upload_batch
  set status = 'ROLLED_BACK',
      rolled_back_by = auth.uid(),
      rolled_back_at = rollback_at_value
  where batch_id = $1
  returning * into batch_row;

  update core.forecast_data_change
  set rolled_back_at = rollback_at_value
  where batch_id = $1;

  insert into core.audit_log(actor, action, target_type, target_id, after)
  values (auth.uid(), 'IMPORT_BATCH_ROLLED_BACK', 'upload_batch', $1::text, to_jsonb(batch_row));

  return batch_row;
end;
$$;

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.column_mapping enable row level security;
alter table core.validation_error enable row level security;
alter table core.import_rollback_snapshot enable row level security;
alter table core.forecast_data_change enable row level security;

revoke all on core.upload_batch from anon;
revoke all on core.import_staging from anon;
revoke all on core.column_mapping from anon;
revoke all on core.validation_error from anon;
revoke all on core.import_rollback_snapshot from anon;
revoke all on core.forecast_data_change from anon;
revoke all on core.import_batch_summary from anon;

grant select, insert, update, delete on core.upload_batch to authenticated;
grant select, insert, update, delete on core.import_staging to authenticated;
grant select, insert, update, delete on core.column_mapping to authenticated;
grant select, insert, update, delete on core.validation_error to authenticated;
grant select on core.import_rollback_snapshot, core.forecast_data_change to authenticated;
grant select on core.import_batch_summary to authenticated;
grant usage, select on all sequences in schema core to authenticated;

drop policy if exists upload_batch_owner_select on core.upload_batch;
create policy upload_batch_owner_select on core.upload_batch
for select to authenticated
using (
  core.is_active_user()
  and (uploaded_by = auth.uid() or core.is_admin())
);
drop policy if exists upload_batch_admin_mutation on core.upload_batch;
create policy upload_batch_admin_mutation on core.upload_batch
for all to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists import_staging_owner_select on core.import_staging;
create policy import_staging_owner_select on core.import_staging
for select to authenticated using (
  exists (
    select 1 from core.upload_batch as batch
    where batch.batch_id = import_staging.batch_id
      and core.is_active_user()
      and (batch.uploaded_by = auth.uid() or core.is_admin())
  )
);
drop policy if exists import_staging_admin_mutation on core.import_staging;
create policy import_staging_admin_mutation on core.import_staging
for all to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists column_mapping_active_select on core.column_mapping;
create policy column_mapping_active_select on core.column_mapping
for select to authenticated using (core.is_active_user());
drop policy if exists column_mapping_admin_mutation on core.column_mapping;
create policy column_mapping_admin_mutation on core.column_mapping
for all to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists validation_error_owner_select on core.validation_error;
create policy validation_error_owner_select on core.validation_error
for select to authenticated using (
  exists (
    select 1 from core.upload_batch as batch
    where batch.batch_id = validation_error.batch_id
      and core.is_active_user()
      and (batch.uploaded_by = auth.uid() or core.is_admin())
  )
);
drop policy if exists validation_error_admin_mutation on core.validation_error;
create policy validation_error_admin_mutation on core.validation_error
for all to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists rollback_snapshot_admin_select on core.import_rollback_snapshot;
create policy rollback_snapshot_admin_select on core.import_rollback_snapshot
for select to authenticated using (core.is_admin());
drop policy if exists rollback_snapshot_admin_mutation on core.import_rollback_snapshot;
create policy rollback_snapshot_admin_mutation on core.import_rollback_snapshot
for all to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists forecast_data_change_active_select on core.forecast_data_change;
create policy forecast_data_change_active_select on core.forecast_data_change
for select to authenticated using (core.is_active_user());
drop policy if exists forecast_data_change_admin_mutation on core.forecast_data_change;
create policy forecast_data_change_admin_mutation on core.forecast_data_change
for all to authenticated using (core.is_admin()) with check (core.is_admin());

revoke all on function core.import_approved_batch(uuid, text) from public, anon;
revoke all on function core.rollback_import_batch(uuid) from public, anon;
grant execute on function core.import_approved_batch(uuid, text) to authenticated;
grant execute on function core.rollback_import_batch(uuid) to authenticated;
