create schema if not exists core;

do $$ begin
  create type core.app_role as enum ('ADMIN', 'USER');
exception when duplicate_object then null;
end $$;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  department text not null default '',
  role core.app_role not null default 'USER',
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid not null references auth.users(id),
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create or replace function core.touch_updated_at()
returns trigger language plpgsql security definer set search_path = core, public as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists app_user_updated_at on core.app_user;
create trigger app_user_updated_at before update on core.app_user for each row execute function core.touch_updated_at();

create or replace function core.handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = core, public as $$
begin
  insert into core.app_user (user_id, email, name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'name', ''))
  on conflict (user_id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function core.handle_new_auth_user();

create or replace function core.is_admin()
returns boolean language sql stable security definer set search_path = core, public as $$
  select exists (select 1 from core.app_user where user_id = auth.uid() and role = 'ADMIN' and active = true);
$$;

create or replace function core.record_login()
returns void language sql security definer set search_path = core, public as $$
  update core.app_user set last_login_at = now() where user_id = auth.uid();
$$;

create or replace function core.admin_update_user_role(target_user_id uuid, next_role core.app_role)
returns core.app_user language plpgsql security definer set search_path = core, public as $$
declare old_row core.app_user; new_row core.app_user;
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED' using errcode = '42501'; end if;
  if target_user_id = auth.uid() and next_role <> 'ADMIN' then raise exception 'SELF_ROLE_CHANGE_FORBIDDEN' using errcode = '42501'; end if;
  select * into old_row from core.app_user where user_id = target_user_id for update;
  if old_row.user_id is null then raise exception 'USER_NOT_FOUND' using errcode = 'P0002'; end if;
  update core.app_user set role = next_role where user_id = target_user_id returning * into new_row;
  insert into core.audit_log(actor, action, target_type, target_id, before, after)
  values (auth.uid(), 'USER_ROLE_CHANGED', 'app_user', target_user_id::text, to_jsonb(old_row), to_jsonb(new_row));
  return new_row;
end;
$$;

create or replace function core.admin_set_user_active(target_user_id uuid, next_active boolean)
returns core.app_user language plpgsql security definer set search_path = core, public as $$
declare old_row core.app_user; new_row core.app_user;
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED' using errcode = '42501'; end if;
  if target_user_id = auth.uid() and next_active = false then raise exception 'SELF_DEACTIVATION_FORBIDDEN' using errcode = '42501'; end if;
  select * into old_row from core.app_user where user_id = target_user_id for update;
  if old_row.user_id is null then raise exception 'USER_NOT_FOUND' using errcode = 'P0002'; end if;
  update core.app_user set active = next_active where user_id = target_user_id returning * into new_row;
  insert into core.audit_log(actor, action, target_type, target_id, before, after)
  values (auth.uid(), 'USER_ACTIVE_CHANGED', 'app_user', target_user_id::text, to_jsonb(old_row), to_jsonb(new_row));
  return new_row;
end;
$$;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;
revoke all on schema core from anon;
revoke all on schema analytics from anon;
revoke all on all tables in schema core from anon;
revoke all on all tables in schema analytics from anon;
revoke all on all sequences in schema core from anon;
revoke all on function core.is_admin() from anon;
revoke all on function core.admin_update_user_role(uuid, core.app_role) from anon;
revoke all on function core.admin_set_user_active(uuid, boolean) from anon;
grant usage on schema core to authenticated;
grant select on core.app_user to authenticated;
grant execute on function core.is_admin() to authenticated;
grant execute on function core.record_login() to authenticated;
grant execute on function core.admin_update_user_role(uuid, core.app_role) to authenticated;
grant execute on function core.admin_set_user_active(uuid, boolean) to authenticated;

drop policy if exists app_user_select on core.app_user;
create policy app_user_select on core.app_user for select to authenticated using (user_id = auth.uid() or core.is_admin());
drop policy if exists audit_log_select on core.audit_log;
create policy audit_log_select on core.audit_log for select to authenticated using (core.is_admin());

do $$ begin
  if to_regclass('core.leadtime_plan') is not null then
    execute 'drop policy if exists leadtime_plan_user_select on core.leadtime_plan';
    execute 'create policy leadtime_plan_user_select on core.leadtime_plan for select to authenticated using (auth.uid() is not null)';
    execute 'drop policy if exists leadtime_plan_admin_mutation on core.leadtime_plan';
    execute 'create policy leadtime_plan_admin_mutation on core.leadtime_plan for all to authenticated using (core.is_admin()) with check (core.is_admin())';
  end if;
  if to_regclass('core.usage_profile') is not null then
    execute 'drop policy if exists usage_profile_user_select on core.usage_profile';
    execute 'create policy usage_profile_user_select on core.usage_profile for select to authenticated using (auth.uid() is not null)';
    execute 'drop policy if exists usage_profile_admin_mutation on core.usage_profile';
    execute 'create policy usage_profile_admin_mutation on core.usage_profile for all to authenticated using (core.is_admin()) with check (core.is_admin())';
  end if;
end $$;
