-- STEP 2 RLS 정책은 supabase/migrations/20260828000100_create_auth_rbac.sql에 있습니다.
-- 기존 수업용 using(true) 쓰기 정책을 재생성하지 않도록 이 파일은 안내용으로 유지합니다.
-- anon은 core/analytics schema usage와 table privilege가 없고,
-- authenticated USER는 조회만, ADMIN은 RLS를 통과한 업무 mutation만 수행합니다.
